[versions]
kotlin-version = "2.0.0"
ktor-version = "3.2.2"
logback-version = "1.5.25"
kotlin-mongo-driver-version = "5.5.1"
gcp-secret-manager-version = "2.81.0"
bcrypt-version = "0.10.2"
koin-version = "4.0.3"
firebase-admin-version = "9.2.0"
gcp-vertexai-version = "1.7.0"

[libraries]
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor-version" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor-version" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor-version" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor-version" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor-version" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor-version" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-version" }
kotlin-mongo-driver = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version.ref = "kotlin-mongo-driver-version" }
kotlin-mongo-bson = { module = "org.mongodb:bson-kotlinx", version.ref = "kotlin-mongo-driver-version" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor-version" }
ktor-server-html = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor-version" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-version" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor-version" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-version" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor-version" }
ktor-server-resources = { module = "io.ktor:ktor-server-resources", version.ref = "ktor-version" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor-version" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor-version" }
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt-version" }
gcp-secret-manager = { module = "com.google.cloud:google-cloud-secretmanager", version.ref = "gcp-secret-manager-version" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-version" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin-version" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin-version" }
firebase-admin = { module = "com.google.firebase:firebase-admin", version.ref = "firebase-admin-version" }
gcp-vertexai = { module = "com.google.cloud:google-cloud-vertexai", version.ref = "gcp-vertexai-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }
shadow = { id = "com.gradleup.shadow", version = "8.3.6" }
gcloud-appengine = { id = "com.google.cloud.tools.appengine", version = "2.8.0" }
